# Generated by Django 4.1.5 on 2023-02-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_alter_distanceadditionalprice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distanceadditionalprice", options={"ordering": ("-is_active",)},
        ),
    ]
