# Generated by Django 4.1.5 on 2023-02-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_alter_distanceadditionalprice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distancebasepricing",
            options={"ordering": ("-is_active", "up_to_distance")},
        ),
        migrations.AlterModelOptions(
            name="timemultiplierfactor",
            options={"ordering": ("-is_active", "up_to_time")},
        ),
    ]
